/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadolibre;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Viveros
 */
public class JIFAltaProductor extends javax.swing.JInternalFrame {
    private static Connection con;
    private static PreparedStatement stmt;
    private static final String driver="com.mysql.cj.jdbc.Driver";      
    private static final String user="bl00per";
    private static final String pass="123456";
    private static final String url="jdbc:mysql://localhost:3306/bdprueba?serverTimezone=UTC";
    ResultSet rs,rs2;
    int idProd;
    /**
     * Creates new form JIFAltaProductor
     */
    public JIFAltaProductor() {
        initComponents();
        con=null;
        stmt=null;
        try{
            Class.forName(driver);
            // Nos conectamos a la bd
            con= DriverManager.getConnection(url, user, pass);            
            stmt = con.prepareStatement("SELECT * FROM productos;");
            rs=stmt.executeQuery();

            while (rs.next()){
                cmbProducto.addItem(rs.getString("nombre"));
                
            }
        }
        // Si existe algún error mostramos un mensaje de error
        catch (ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,"Error: " + e);
        }
    }

    public void guardaProductor() throws InstantiationException, SQLException {
        // Reseteamos a null la conexion a la bd
        //con=null;
        //stmt=null;
        try{
            Class.forName(driver);
            // Nos conectamos a la bd
            con= DriverManager.getConnection(url, user, pass);
            stmt = con.prepareStatement("INSERT INTO productores (nombre,nombreproducto,tiempoelaboracion,almacenamiento)values(?,?,?,?)");
            stmt.setString(1, txtNombre.getText());
            stmt.setString(2,(cmbProducto.getSelectedItem().toString()));
            stmt.setInt(3,Integer.valueOf(txtTmpProducto.getText()));
            stmt.setInt(4, Integer.valueOf( txtAlmacenamiento.getText()));
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Se agregó el producto");
        }
        // Si existe algún error mostramos un mensaje de error
        catch (ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,"Error: " + e);
        }
        //con.close();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTmpProducto = new javax.swing.JTextField();
        lblrango = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAlmacenamiento = new javax.swing.JTextField();
        btnGuardaProductor = new javax.swing.JButton();

        setClosable(true);
        setTitle("Alta de productor");

        jLabel1.setText("Nombre de productor:");

        jLabel2.setText("Producto a elaborar:");

        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tiempo de elaboración*:");

        lblrango.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblrango.setForeground(new java.awt.Color(153, 153, 153));
        lblrango.setText("*El tiempo de elaboración debes estar entre el rango X y Y");

        jLabel5.setText("Capacidad de almacenamiento:");

        btnGuardaProductor.setText("Guardar Productor");
        btnGuardaProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaProductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlmacenamiento))
                    .addComponent(lblrango)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTmpProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardaProductor)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTmpProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrango)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnGuardaProductor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardaProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaProductorActionPerformed
        try {
            guardaProductor();
        } catch (InstantiationException ex) {
            Logger.getLogger(JIFAltaProductor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JIFAltaProductor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardaProductorActionPerformed

    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
        //con=null;
        //stmt=null;
        try{
            Class.forName(driver);
            // Nos conectamos a la bd
            con= DriverManager.getConnection(url, user, pass);            
            stmt = con.prepareStatement("SELECT minprod,maxprod FROM productos where nombre=?");
            stmt.setString(1, cmbProducto.getSelectedItem().toString());
            rs2=stmt.executeQuery();

            if (rs2.next()){
                lblrango.setText("El tiempo de elaboración debes estar entre "+ rs2.getString("minprod") +" y "+ rs2.getString("maxprod"));
            }
        }
        // Si existe algún error mostramos un mensaje de error
        catch (ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_cmbProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardaProductor;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblrango;
    private javax.swing.JTextField txtAlmacenamiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTmpProducto;
    // End of variables declaration//GEN-END:variables
}
